tasks:
  - command: gp await-port 3000 && gp preview $(gp url 3000)/tech-interview-handbook/
  - before: cd website/
    init: yarn install
    command: yarn start
ports:
  - port: 3000
    onOpen: ignore
